site_name: Chitung-python Docs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: 黑暗模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 明亮模式


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition # 提示块
  - footnotes # 脚注
  - meta # 定义元数据, 通过文章上下文控制, 如disqus
  - pymdownx.caret # 下划线上标
  - pymdownx.tilde # 删除线下标
  - pymdownx.critic # 增加删除修改高亮注释, 可修饰行内或段落
  - pymdownx.details # 提示块可折叠
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.mark # 文本高亮
  - pymdownx.smartsymbols # 符号转换
  - pymdownx.superfences # 代码嵌套在列表里
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - codehilite: # 代码高亮, 显示行号
      guess_lang: false
      linenums: true
  - toc: # 锚点
      permalink: 🔗
  - pymdownx.arithmatex # 数学公式
  - pymdownx.betterem: # 对加粗和斜体更好的检测
      smart_enable: all
  - pymdownx.magiclink: # 自动识别超链接
      repo_url_shorthand: true
      user: "nullqwertyuiop"
      repo: "Chitung-python"
      social_url_shorthand: true
      repo_url_shortener: true
  - pymdownx.tasklist: # 复选框checklist
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
